import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import BackToTop from "@/components/TopButton";
import { LangProvider } from "@/context/LangContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className=" text-[#333] ">
        <LangProvider>
          <Header />
          {children}
          <BackToTop />
          <Footer />
        </LangProvider>
      </body>
    </html>
  );
}
